### ISSUE TITLE
Add Azure DevOps build

### ISSUE THREAD

**Issue by Szer** [Hopac/Hopac#189]
Travis is pretty slow. Azure is much more powerful tool to build stuff.

I've tested this on my Azure DevOps account and it builds perfectly with only this yaml:
```yaml
pool:
  vmImage: 'vs2017-win2016'

steps:
- script: fake.cmd build
  displayName: 'Build'
```

Build results:
https://szer.visualstudio.com/Hopac/_build/results?buildId=21&view=logs
